### PR TITLE
Coinbase and MacOS

### PR DESCRIPTION
**Pull request by TheSerapher**
Hey @cmallwitz,

Since Yahoo had issues again today and figured I'll give it a go and try to add Coinbase Exchange API since that data is also public available.

It works but of course it's very rudimentary since I tried to find out how extensions work to write my own but figured why bother.

Since I am using MacOS I also added some changes to the `compile.sh` that should allow other MacOS users to run it as well :)

### CODE REVIEW

**Comment by TheSerapher** [comment]
I'll give it a go :)

**Comment by TheSerapher** [comment]
I have added something but I can't really test it on MacOS since I am not able to figure out how to get that unohelper python module to work. But it could be expanded on later.

**Comment by cmallwitz** [comment]
Re: examples.ods - diff-ing binary files is a bit difficult but I can't actually see any changes when I open your version?

**Comment by TheSerapher** [comment]
Oh my bad! Just added the test file … I’ll add it later when I am awake again.

**Comment by TheSerapher** [comment]
Struggling to get this document to work with the new symbols - I will take another look soon but so far it just throws weird stuff.

**Comment by TheSerapher** [comment]
Haven't had the time to look at it further but will push the example - maybe you can make some sense out of it and somehow add the new datasource properly?

**Comment by cmallwitz** [comment]
Checkout new release version 3.1.0 - Danke!

**Pull request merged**
